import { runReplay, calibrationScoresSet } from "@/lib/pipeline/replay";
import { conformalQuantile, empiricalCoverage } from "@/lib/stats/conformal";
const s = runReplay();
console.log("MAE km physics:", Object.fromEntries(Object.entries(s.maeKm.physics).map(([k,v])=>[k,+v.toFixed(2)])));
console.log("MAE km model  :", Object.fromEntries(Object.entries(s.maeKm.model).map(([k,v])=>[k,+v.toFixed(2)])));
const g=s.results.filter(r=>r.sizeClass==="GIANT");
const p72=g.reduce((a,b)=>a+b.physicsKm.h72,0)/g.length, m72=g.reduce((a,b)=>a+b.modelKm.h72,0)/g.length;
console.log(`GIANT 72h: ${p72.toFixed(2)} -> ${m72.toFixed(2)} km (${(((p72-m72)/p72)*100).toFixed(1)}% better) target<25:`, m72<25?"PASS":"FAIL");
console.log("bySeason:", Object.fromEntries(Object.entries(s.bySeason).map(([k,v])=>[k,`${v.n}c ${v.maeKm72.toFixed(1)}km`])));
const sc=calibrationScoresSet(); const q=conformalQuantile(sc.h72,0.9);
console.log("cone90 km:", {h24:+conformalQuantile(sc.h24,0.9).toFixed(1),h48:+conformalQuantile(sc.h48,0.9).toFixed(1),h72:+q.toFixed(1)}, "coverage:", empiricalCoverage(sc.h72,q).toFixed(3), "n:", sc.h72.length);
